### ISSUE TITLE
Add package.json to node/

### ISSUE THREAD

**Issue by cbrewster** [psychoss/rust-note#1]
This is looking pretty awesome! Although I noticed that the `node` directory didn't have a `package.json` which means I had to install `koa` and `koa-send` by hand. You should create a `package.json` so its easier to install all of the node dependencies.

**Comment by psychoss** [comment]
@ConnorGBrewster  Thanks for your advice，I have added it。

**Comment by cbrewster** [comment]
Looks like this was fixed in commit 64c1c46.
